# Generated by Django 4.2.17 on 2025-01-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='numero_personas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
